server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/autotest?useSSL=false
      username: root
      password: 19900205xu
mybatis:
  type-aliases-packag: com.course.model
  mapper-locations:
     - mapper/*



